version: '3'
services:

  local-rag:
    container_name: local-rag
    image: local-rag-local-ollama-custom
    restart: unless-stopped
    ports:
      - '8501:8501/tcp'
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
